feat(meeting): initialize recording property from the locus info
webex/webex-js-sdk pull request #1889
Opened 2020-09-21 23:45 UTC by akoushke

Fixes #[INSERT LINK TO ISSUE NUMBER]
SPARK-178087
---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2020-09-21 23:47 UTC, akoushke commented on packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
> +    this.recording = attrs.locus?.controls.record ? {state: RECORDING_STATE.IDLE, modifiedBy: '', lastModified: ''} : null;
I do prefer to define classes for different controls with an abstract called `Control` and have classes `Recording` `Locked` etc etc.

2020-09-22 00:23 UTC, arun3528 requested changes
This logic needs to be moved in the locusInfo updateControl section , Placing it here wont trigger an event to the developer initially on recording ,

2020-09-22 01:02 UTC, akoushke commented
> This logic needs to be moved in the locusInfo updateControl section , Placing it here wont trigger an event to the developer initially on recording ,

and it shouldn't trigger an event at the initial level IMO.  events get triggered after the setup and `recording` should be defined before that the event setup.

2020-09-23 00:14 UTC, akoushke commented
I tested this and worked as expected.

2020-09-23 01:28 UTC, akoushke commented
1:1 
![Screen Shot 2020-09-22 at 6 27 35 PM](https://user-images.githubusercontent.com/14226615/93953988-6e90cf00-fd01-11ea-83f3-3bd557f02051.png)
meeting
![Screen Shot 2020-09-22 at 6 28 26 PM](https://user-images.githubusercontent.com/14226615/93954002-76e90a00-fd01-11ea-9407-3ea2878dba3c.png)

2020-09-23 04:04 UTC, arun3528 commented on packages/node_modules/@webex/plugin-meetings/src/locus-info/controlsUtils.js
> +        previous?.record?.recording, current?.record?.recording
nice so this will check undefined with false

2020-09-23 04:04 UTC, arun3528 approved these changes

2020-09-23 17:52 UTC, merged