feat(services): add override catalog
webex/webex-js-sdk pull request #1906
Opened 2020-10-13 22:05 UTC by InteractiveTimmy

### Description

*IN DEVELOPMENT: NEEDS TESTING*

The scope of the changes in this pull request are to add an`override` catalog that supersedes the priority of the `postauth` catalog. This is primarily for improving test flow, but could be used in cases of service outages.

2020-10-14 21:49 UTC, InteractiveTimmy commented
A unit test locally fails that is unrelated to these changes:

```
Credentials
      Token
        #initialize()
          ✖ computes expires_in and refresh_token_expires_in if not specified
```

2020-10-14 22:15 UTC, mwegman requested changes
Can you provide integration tests for this?

2020-10-15 18:50 UTC, chrisadubois commented on packages/node_modules/@webex/webex-core/src/lib/services/service-catalog.js
> +        collectiong: false
collecting

2020-10-28 21:48 UTC, InteractiveTimmy commented on packages/node_modules/@webex/webex-core/src/lib/services/service-catalog.js
> +        collectiong: false
fixed!

2020-10-28 21:49 UTC, InteractiveTimmy commented
> Can you provide integration tests for this?

Added the integration test that covers the entire stack @mwegman

2020-10-28 21:53 UTC, chrisadubois approved these changes

2020-11-04 16:05 UTC, adamweeks commented
@mwegman can you re-review or remove your request for changes?

2020-11-13 02:30 UTC, chrisadubois commented
Merge it !!!

2020-11-13 17:38 UTC, mwegman approved these changes

2020-11-16 16:31 UTC, merged