feat(space-classification): allow user to create a classified space
webex/webex-js-sdk pull request #1916
Opened 2020-10-28 08:10 UTC by AMANDUA

This PR comprises of code changes to allow user to create a classified space

Fixes #[INSERT LINK TO ISSUE NUMBER]

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-176840
---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2020-10-28 14:36 UTC, adamweeks requested changes
Thanks for adding this support. Could you please add an additional test on the `create` function that will call with this param?

2020-10-28 14:36 UTC, adamweeks commented on packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js
> +    if (!params.isDefaultClassification && params.classificationId) {
Please add these additional params to the jsdoc on the params object on the `create` function near line 167.

2020-10-28 20:57 UTC, adamweeks commented
@AMANDUA 

> I tried adding test with existing orgs but the integration tests are failing saying org is not having space classifications enabled...

If we aren't able to get any integration orgs for this feature, perhaps you can add a test that expects the error when the feature isn't enabled at least.

2020-10-29 04:38 UTC, AMANDUA commented
> @AMANDUA
> 
> > I tried adding test with existing orgs but the integration tests are failing saying org is not having space classifications enabled...
> 
> If we aren't able to get any integration orgs for this feature, perhaps you can add a test that expects the error when the feature isn't enabled at least.

yes that sounds good to me...

2020-10-29 12:05 UTC, AMANDUA commented
Added the test @adamweeks  
![image](https://user-images.githubusercontent.com/17237753/97568231-f195fb00-1a0c-11eb-85d9-07e67e37b276.png)

and passed the  CI.

But few integration tests are failing , saying timeout
![image](https://user-images.githubusercontent.com/17237753/97568856-1be7b880-1a0d-11eb-90bd-aeb820aece98.png)

2020-10-29 16:01 UTC, adamweeks approved these changes
Merging. The test failures are the same failures as master branch currently experiencing: https://app.circleci.com/pipelines/github/webex/webex-js-sdk/4124/workflows/7d5fae21-b726-48ca-ac1b-dc3714fb90c7/jobs/29488

2020-10-29 16:02 UTC, merged