feat(meetings): fail meeting join if peer connection isn't stable
webex/webex-js-sdk pull request #1994
Opened 2021-01-28 17:56 UTC by adamweeks

Fixes [SPARK-194866](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-194866)

Replaces #1983

2021-01-28 18:09 UTC, mwegman requested changes

2021-01-28 18:09 UTC, mwegman commented on packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
> +              throw new Error(`Peer Connection NOT CONNECTED after ${PC_BAIL_TIMEOUT / 1000} seconds since trying to join... Will now be ending the call`);
This does nothing. It definitely doesn't reject the promise above.

2021-01-28 18:12 UTC, mwegman commented on packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
> +              throw new Error(`Peer Connection NOT CONNECTED after ${PC_BAIL_TIMEOUT / 1000} seconds since trying to join... Will now be ending the call`);
You would need to create a promise that is rejected in this if statement

2021-01-29 17:12 UTC, arun3528 commented on packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
> +            this.on(EVENT_TRIGGERS.MEETING_MEDIA_CONNECTED, () => {
I dont think we need to send a connected event as we already have media ready , Both media:ready and connected will trigger at the same time

2021-01-29 17:14 UTC, arun3528 reviewed
Lets check on the media:connected event , Feel its wont be that helpful anyways we are resolving promise and sending media:Ready event

2021-02-05 17:13 UTC, arun3528 approved these changes

2021-02-05 17:25 UTC, mwegman approved these changes

2021-02-05 17:25 UTC, merged