fix(upload): add abort function on file upload for webex
webex/webex-js-sdk pull request #1996
Opened 2021-02-04 16:29 UTC by arjunkesava

Fixes [SPARK](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-203178)

On WebEx, when user uploads a file we should check for file limit and restrict the user to upload files within specified limit or 2048 MB by default

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2021-02-04 18:20 UTC, mwegman requested changes
Code looks good. Please add a test for it.

2021-02-08 17:15 UTC, arjunkesava commented
Thank you @mwegman for review.
This PR is to add an ability to abort the upload process for file.
The upload function in the webcore file doesn’t have any test cases until now.
So, if I write a test case for _uploadAbortSession, then I have to write the test cases for the entire upload function which will take a lot more time than expected.
Files team is waiting on the results of this PR. Could you please approve it.
I will add the test cases in my next PR (there is some more work coming on the way)

2021-02-09 18:25 UTC, mwegman approved these changes

2021-02-10 20:55 UTC, arun3528 commented
@mwegman  should we know when the sessions get aborted as we need to know how many times its happens !? @arjunkesava 
 do we have any metrics around it as there will be some meetings we need to triage and if we dont have log file

2021-02-10 21:04 UTC, adamweeks commented
@arun3528 the metrics would have to be on the server side to check the DELETE requests. We are not adding client metrics in the SDK outside of the meetings plugin for now.

2021-02-11 03:09 UTC, arun3528 commented
If someone is going to track the if deletes are spiking then we might have to re visit on how much we log , good for now

2021-02-11 19:31 UTC, adamweeks commented
@arjunkesava could you please squash the commits into one? We utilize commit messages to generate the [changelog](https://github.com/webex/webex-js-sdk/blob/master/CHANGELOG.md)

2021-02-14 18:10 UTC, arjunkesava commented
@adamweeks @mwegman 

I had rebased it with latest upstream master and also squashed into a single commit. Please do note.

2021-02-15 16:24 UTC, adamweeks approved these changes

2021-02-15 16:24 UTC, adamweeks commented
@arjunkesava Thanks for making those changes, approved!

2021-02-15 16:24 UTC, merged