fix(plugin-meetings): added userId, orgId and meetingId for upload logs
webex/webex-js-sdk pull request #2003
Opened 2021-02-10 20:46 UTC by arun3528

[ ⛔️ ----- REMOVE THIS SECTION  ----- ⛔️

Hey there,\
Thank you for taking the time to improve our code! 🙂\
Please let us know why this change is necessary. \
This ensures our reviewers understand the impact of your change.

⛔️ ----- SECTION END  ----- ⛔️]

Fixes #[INSERT LINK TO ISSUE NUMBER]

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2021-02-11 17:49 UTC, adamweeks requested changes
Can you split the commits into the proper areas? One for meetings, one for i-p-support?

2021-02-11 20:47 UTC, arun3528 commented
hey @adamweeks  whats the most easy way to do it

2021-02-11 20:56 UTC, adamweeks commented
@arun3528 you can rebase your commit into two. Here's a good doc on it https://emmanuelbernard.com/blog/2014/04/14/split-a-commit-in-two-with-git/

2021-02-15 16:11 UTC, arun3528 commented
@adamweeks fixed the review comments

2021-02-15 17:59 UTC, adamweeks commented
Looks like you lost the changes to the support plugin and [this commit](https://github.com/webex/webex-js-sdk/pull/2003/commits/b1059c8436b67878b25fa1db66b12e36fad6b7da) has changes to the meetings plugin even though the scope message says `support`

2021-02-15 18:58 UTC, adamweeks commented on packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
> +          function: 'leave'
```suggestion
          function: 'setUpLocusInfoMediaInactiveListener'
```

2021-02-15 18:59 UTC, adamweeks commented on packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
> +            function: 'leave'
```suggestion
            function: 'join'
```

2021-02-15 18:59 UTC, adamweeks commented on packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
> +            function: 'leave'
```suggestion
            function: 'addMedia'
```

2021-02-16 15:42 UTC, adamweeks approved these changes

2021-02-16 15:42 UTC, merged