docs(api): remove phone plugin reference
webex/webex-js-sdk pull request #2009
Opened 2021-02-12 16:52 UTC by abailey-dev

Removes phone plugin references in the SDK docs "calling" section and renames section to "meetings".
Fixes #SPARK-117145

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2021-02-12 22:18 UTC, adamweeks requested changes
Looks like naming the section the same as the plugin is causing issues with double expanding. This seems to fix that issue and gives a little detail on what the section is for.

2021-02-12 22:18 UTC, adamweeks commented on documentation/config.yml
> +  - name: Meetings
```suggestion
  - name: Webex Meetings
    description: |
      The meetings plugin allows browser users to embed Webex meetings into their application.
  
```

2021-02-16 14:10 UTC, abailey-dev commented on documentation/config.yml
> +  - name: Meetings
Thanks!

2021-02-16 17:06 UTC, adamweeks commented
@abailey-dev you've got a merge conflict, otherwise this looks good!

2021-02-16 22:16 UTC, adamweeks approved these changes

2021-02-16 22:16 UTC, merged