feat(webex-core/src/lib/services): allow for options to be passed thr…
webex/webex-js-sdk pull request #2081
Opened 2021-05-21 16:43 UTC by shnaaz

…ough to sendUserActivation

Allow for extra options to be passed through to sendUserActivation when sending the activation and to use license service.
This will be useful for webex web app in user activation flow to validate user.

Fixes #[INSERT LINK TO ISSUE NUMBER]

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2021-05-24 15:57 UTC, mwegman approved these changes

2021-05-25 21:48 UTC, taymoork2 requested changes
1. Amend the changes requested into the 1st commit
2. Rewrite first commit's scope to `feat(webex-core)`
3. Rewrite second commit's scope to `test(webex-core)`

2021-05-25 21:48 UTC, taymoork2 commented on packages/node_modules/@webex/webex-core/src/lib/services/services.js
> +    email, reqId, token, activationOptions
new line params for readability
```suggestion
    email,
    reqId,
    token,
    activationOptions
```

2021-05-25 21:48 UTC, taymoork2 commented on packages/node_modules/@webex/webex-core/src/lib/services/services.js
> +          email, reqId, token, activationOptions
new line params for readability
```suggestion
          email,
          reqId,
          token,
          activationOptions
```

2021-05-25 21:48 UTC, taymoork2 commented on packages/node_modules/@webex/webex-core/src/lib/services/services.js
> +    email, reqId = 'WEBCLIENT', forceRefresh = false, activationOptions = {}
new line params for readability
```suggestion
    email,
    reqId = 'WEBCLIENT',
    forceRefresh = false,
    activationOptions = {}
```

2021-05-25 21:48 UTC, taymoork2 commented on packages/node_modules/@webex/webex-core/src/lib/services/services.js
> +            email, reqId, countryCode, timeZone: timezone, ...activationOptions
new params for readability
```suggestion
            email,
            reqId,
            countryCode,
            timeZone: timezone,
            ...activationOptions
```

2021-05-26 01:10 UTC, lalli-flores commented
@shnaaz, please make sure to keep your commits cleanly separate changes as stated in the contributing guide, as they translate into the changelog. If you're addressing feedback, do not create another commit, you need to rebase your existing commit

2021-05-28 18:03 UTC, taymoork2 approved these changes
LGTM

2021-05-28 19:12 UTC, merged