Allow share to be cancellable when using native share stop
webex/webex-js-sdk pull request #2094
Opened 2021-06-08 00:54 UTC by taymoork2

Fixes #[SPARK-238680](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-238680)

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2021-06-08 01:01 UTC, taymoork2 commented
@arun3528 
Screenshare takeover is not working correctly, it does not end the local screenshare nor does it resume the not ended screenshare after the remote screenshare ends

2021-06-08 15:15 UTC, mwegman requested changes

2021-06-08 15:15 UTC, mwegman commented on packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
> +          newShareStatus = SHARE_STATUS.NO_SHARE;
I don't believe you need to set `newShareStatus`. It should get set by `this.stopShare()`

2021-06-08 18:46 UTC, taymoork2 commented
Integration tests are failing consistently moving to draft

2021-06-10 17:09 UTC, mwegman approved these changes

2021-06-11 18:17 UTC, merged