fix(plugin-meetings): emit meeting:self:lobbyWaiting and meeting:self…
webex/webex-js-sdk pull request #2105
Opened 2021-06-23 04:14 UTC by arun3528

…:guestAdmitted for webex meeting

[ ⛔️ ----- REMOVE THIS SECTION  ----- ⛔️

Hey there,\
Thank you for taking the time to improve our code! 🙂\
Please let us know why this change is necessary. \
This ensures our reviewers understand the impact of your change.

⛔️ ----- SECTION END  ----- ⛔️]

Fixes #[INSERT LINK TO ISSUE NUMBER]

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2021-06-24 17:12 UTC, mwegman requested changes

2021-06-24 17:12 UTC, mwegman commented on packages/node_modules/@webex/plugin-meetings/src/locus-info/selfUtils.js
> +SelfUtils.isLocusGuestUnadmitted = (check) => check && check.joinedWith && check.joinedWith?.intent?.type === _WAIT_ && check.state === _IDLE_;
```suggestion
SelfUtils.isLocusGuestUnadmitted = (check) => check && check.joinedWith?.intent?.type === _WAIT_ && check.state === _IDLE_;
```

2021-06-28 14:54 UTC, arun3528 commented on packages/node_modules/@webex/plugin-meetings/src/locus-info/selfUtils.js
> +SelfUtils.isLocusGuestUnadmitted = (check) => check && check.joinedWith && check.joinedWith?.intent?.type === _WAIT_ && check.state === _IDLE_;
done

2021-06-29 20:48 UTC, mwegman approved these changes

2021-06-29 20:48 UTC, merged