fix: don't send unmutedByOthers when being removed from a meeting
webex/webex-js-sdk pull request #2111
Opened 2021-07-07 13:49 UTC by marcin-bazyl

I've found this when testing being removed from a PMR meeting.

2021-07-07 15:49 UTC, mwegman approved these changes

2021-07-08 23:30 UTC, lalli-flores reviewed
Thanks for finding this bug and adding a fix!
Can you update your commit message so it's clearer for someone without context on the changelog? Also, don't forget to add a scope of your change.

Something like:
```
fix(meetings): check current user is still in-meeting before unmuting

Scenario found while testing a user being removed from a PMR

2021-07-09 09:24 UTC, lalli-flores requested changes
we can merge once commit has been updated

2021-07-09 09:52 UTC, marcin-bazyl commented
I've updated the commit message. Thanks.

2021-07-09 09:54 UTC, lalli-flores approved these changes

2021-07-16 00:15 UTC, merged