feat(meetings): added logging to utils, unit tests
webex/webex-js-sdk pull request #2125
Opened 2021-07-21 17:17 UTC by jonniespratley

This PR adds logging on user device setup and changes. This is meant to give more diagnostic information when debugging media issues.

Fixes #[239692](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-239692)

2021-07-22 06:14 UTC, lalli-flores requested changes
Let's make sure commit message is good for a changelog. Maybe something like:
```
feat(meetings): log media device settings on mute events
```

I don't see the logging happening when `addMedia()` is being called, what happened to those changes?

2021-07-22 06:14 UTC, lalli-flores commented on packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
> +        MeetingUtil.handleAudioLogging(this.mediaProperties.videoTrack);
```suggestion
        MeetingUtil.handleVideoLogging(this.mediaProperties.videoTrack);
```

2021-07-24 00:07 UTC, lalli-flores approved these changes

2021-07-24 03:45 UTC, jonniespratley commented
🥳

2021-07-26 23:32 UTC, merged