docs(plugin-meetings): updated docs with known limitation about remote sharing
webex/webex-js-sdk pull request #2179
Opened 2021-09-09 21:13 UTC by emanuallan

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-254773

2021-09-10 15:14 UTC, emanuallan commented
Should i provide background info to the developers? I didnt think theyd be interested so I kept it out

ex. 

"There is a known limitation in the SDK that you can only register for events like `meeting:startedSharingRemote` on the meeting object, 
however, you can only do that after you've received the `meeting:added` event notification with the meeting payload. In the case when a host has already begun sharing before a participant joins, the registration for `meeting:startedSharingRemote` happens too late (after the SDK code that would send that event is already executed)"

2021-09-10 19:35 UTC, lalli-flores commented
@emanuallan, yes adding some context on the topic would be helpful to developers. This way they can determine if the use case applies to them or not.
Although, I wouldn't call it "an SDK limitation" that's how eventing works

2021-09-10 19:40 UTC, lalli-flores commented on packages/node_modules/@webex/plugin-meetings/README.md
> +##### Not seeing remote share if host started sharing screen before participant joins
Maybe add a section for potential other caveats in the future?
```suggestion
### Event Caveats
#### Not seeing remote share if host started sharing screen before participant joins
```

2021-09-10 19:40 UTC, lalli-flores commented on packages/node_modules/@webex/plugin-meetings/README.md
> +Then you set the srcObject of the video element to that stream to be able to see it
Explain a little more why this is necessary

2021-09-13 15:46 UTC, emanuallan commented
Updated the docs with your suggestions @lalli-flores , feel free to review

2021-09-15 21:50 UTC, lalli-flores requested changes
I think this would be easier to follow if you divide the explanation into 3 sections:
#### Context
#### Problem
#### Solution

2021-09-15 21:50 UTC, lalli-flores commented on packages/node_modules/@webex/plugin-meetings/README.md
> +What apps typically do is call `join()` and then `addMedia()` with `options.mediaSettings.receiveShare=true`
I think the context would be easier to follow if it's outlines as a series of steps
```
When trying to receive screen share in an application, standard plugin-meeting workflow is as follow:
1. Set event listener for `media:ready`
2. Call `join()`
3. Call `addMedia()` with `options.mediaSettings.receiveShare=true`
4. Wait to receive an event from `media:ready` with payload `type=remoteShare` that contains the remote share media stream
5. Set `srcObject` of a `video` element in the application to the previously obtained media stream
(e.g. `document.getElementById('remote-screen').srcObject = media.stream`)

2021-09-17 17:43 UTC, merged