fix(plugin-meetings): isRecording shows which member started recording
webex/webex-js-sdk pull request #2198
Opened 2021-09-29 17:36 UTC by emanuallan

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-189023?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=tr

Previously `this.parsedLocus.controls.modifiedBy` was being used to get the `recordingId`, but that doesn't exist (always `undefined`, and thus the reason why `isRecording` is always `false` when comparing id's). Changed it to the correct reference `this.parsedLocus.controls.record.modifiedBy` and now it correctly gets the id

![Screen Shot 2021-09-29 at 12 33 57 PM](https://user-images.githubusercontent.com/22531461/135320126-ba9de23e-a439-4531-a83a-f9571deba599.png)
![Screen Shot 2021-09-29 at 1 55 51 PM](https://user-images.githubusercontent.com/22531461/135323052-948bedb6-8d55-4364-a510-83bef79cd0a6.png)

2021-09-30 16:30 UTC, arun3528 approved these changes

2021-09-30 22:59 UTC, lalli-flores requested changes
@emanuallan can you make your commit message more meaningful for the changelog?
ex:
```
fix(meetings): isRecording shows which member started meeting recording

2021-10-01 15:46 UTC, emanuallan commented
@lalli-flores addressed your input, thank you.

2021-10-04 21:13 UTC, lalli-flores commented on packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/index.js
> +      it('should pass the correct id values', () => {
```suggestion
      it('should emit participant update of recordingId ', () => {
```

2021-10-04 22:47 UTC, lalli-flores approved these changes

2021-10-05 20:17 UTC, emanuallan commented
updated test description to be more clearer

2021-10-11 21:13 UTC, merged