fix(plugin-meetingsV2): add sipUrl to body from sipUri
webex/webex-js-sdk pull request #2244
Opened 2021-12-06 21:50 UTC by jonniespratley

- Add conditional to handle adding `sipUrl` to `body`
- Add spec to test for `meetingNumber`

2021-12-06 21:51 UTC, jonniespratley commented
Note: This is with `enabledUnifiedMeetings = true` so I am not sure how the conditional should be in the spec.

2021-12-07 16:47 UTC, arun3528 commented on packages/node_modules/@webex/plugin-meetings/src/config.js
> +      enableUnifiedMeetings: true
turn it off after taking a screen shot of test which passes

2021-12-07 16:48 UTC, arun3528 commented on packages/node_modules/@webex/plugin-meetings/test/integration/spec/space-meeting.js
> +
nice thanks

2021-12-07 16:48 UTC, arun3528 approved these changes
Add the screen shot of the test passing with the toggle

2021-12-07 21:11 UTC, taymoork2 approved these changes
LGTM

2021-12-08 19:41 UTC, lalli-flores requested changes
Can you check why the integration tests are consistently failing?

2021-12-09 07:59 UTC, lalli-flores approved these changes
`plugin-meetings space-meeting alice adds x user as guest to space meeting` integration tests seem to be particularly flaky today

2021-12-09 07:59 UTC, merged