fix(plugin-meetings): add anonymize ip address
webex/webex-js-sdk pull request #2247
Opened 2021-12-07 23:43 UTC by jonniespratley

- Add `ip-anonymize` to handle masking ip address.
- Add unit tests that verify masking in payload

![Screen Shot 2021-12-07 at 3 43 03 PM](https://user-images.githubusercontent.com/320490/145123028-b55775ab-3bfc-42d5-95ec-1e297c27bb33.png)
.

2021-12-09 07:04 UTC, lalli-flores requested changes
Unit tests don't seem to be working.
Let's be a little more specific on what the change is:
```
fix(plugin-meetings): anonymize IP addresses send in metrics

2021-12-09 07:04 UTC, lalli-flores commented on packages/node_modules/@webex/plugin-meetings/src/metrics/index.js
>  // Apply a CIDR /28 format to the IP address
Let's remove this comment, it's not accurate

2021-12-09 08:32 UTC, taymoork2 approved these changes
FISI

2021-12-10 19:10 UTC, lalli-flores approved these changes

2021-12-10 22:07 UTC, merged