docs(plugin-meeting): update samples meetings management
webex/webex-js-sdk pull request #2261
Opened 2022-01-10 22:01 UTC by jonniespratley

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-293018

Updated ui for meetings management:

- Updated CSS to have styled buttons and inputs, as well as utilities for padding/margin. 
- Updated layout to have fixed streams sidebar.
- Updated create meeting form to handle submissions on enter key
- Updated current meetings list to use radio input.
- Added join button below meetings list to join a meeting that was selected by radio.
- Updated leave meeting logic to leave the meeting of the selected meeting radio input.
- Update wdio test.

2022-01-11 14:31 UTC, arun3528 approved these changes
LGTM

2022-01-12 22:50 UTC, jonniespratley commented
LGTM

2022-01-14 00:33 UTC, lalli-flores commented on packages/node_modules/samples/browser-plugin-meetings/index.html
> +              <p class="note">NOTE: This should say what the actions be do..</p>
```suggestion
              <p class="note">NOTE: In order to send audio/video we must request permissions from the user to access camera and microphone. Once we have access, we should add the corresponding media streams to the meeting</p>
```

2022-01-14 00:37 UTC, lalli-flores commented on packages/node_modules/samples/browser-plugin-meetings/index.html
> +              <legend>General Controls</legend>
```suggestion
              <legend>Lock/Unlock</legend>
```

Maybe something to address on the meeting controls PR

2022-01-14 00:40 UTC, lalli-flores requested changes
Please make this and other commits with changes to samples of `docs` type. We should not be making an SDK release by changing things in sample apps.

2022-01-14 13:29 UTC, arun3528 approved these changes
Can you rebase

2022-01-14 20:15 UTC, lalli-flores approved these changes

2022-01-14 20:18 UTC, lalli-flores commented
Merging with sample tests failing.

- Multi Party Calling sample tests are failing - unrelated to these sample changes
- Call with screen share are consistently failing  - unrelated to these sample changes - would need to be addressed separately

2022-01-14 20:18 UTC, merged