fix(plugin-meetings): media not connecting on ipv6 network
webex/webex-js-sdk pull request #2272
Opened 2022-01-18 18:44 UTC by arun3528

# COMPLETES #< INSERT LINK TO ISSUE >

## This pull request addresses

< DESCRIBE THE CONTEXT OF THE ISSUE >

## by making the following changes

< DESCRIBE YOUR CHANGES >

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2022-01-18 20:35 UTC, taymoork2 requested changes

2022-01-18 20:39 UTC, lalli-flores commented on packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/util.js
> +  // remove this once linus supports Ipv6 c line.currently linus rejects SDP with c line having ipv6 candidates we are
```suggestion
  // TODO: remove this once linus supports Ipv6 c line.currently linus rejects SDP with c line having ipv6 candidates we are
```

2022-01-18 20:42 UTC, lalli-flores commented on packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/util.js
> + * convert cline to ipv4
```suggestion
 * Convert C line to IPv4
```

2022-01-19 16:12 UTC, lalli-flores approved these changes

2022-01-19 23:12 UTC, taymoork2 approved these changes
LGTM

2022-01-20 00:30 UTC, lalli-flores commented
Screen sharing sample tests are failing. This is a known failure that needs to be addressed separately.

2022-01-20 00:31 UTC, merged