Fixed syntax error in JSDoc code example for webex.messages.listen()
webex/webex-js-sdk pull request #2316
Opened 2022-04-01 17:31 UTC by tstatler

# COMPLETES (?)

The repo's 'Create Issue' button opens the Webex Developer Support page. I don't see a way to create GitHub issue?

## This pull request addresses

Fixes JSDoc example code snippet for `webex.messages.listen()` method.

## by making the following changes

Adds closing parentheses to example code snippet.

<img width="941" alt="image" src="https://user-images.githubusercontent.com/408952/161312973-cfd9c21a-2b20-4271-b7a2-4db7fe4fed79.png">

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

Ran `npm run build:docs` and confirmed change appears in HTML output (see screenshot).

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [x] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2022-04-02 03:50 UTC, arun3528 commented
thanks

2022-04-02 03:50 UTC, arun3528 approved these changes

2022-04-02 05:11 UTC, taymoork2 requested changes
please edit your commit message to have the proper scopes
`docs(plugin-messages): ...`
The lack of scopes in the commit already suggest that commit-lint was bypassed, and that our releasing tools will treat this a need to publish a new version of the SDK instead of ignoring it

2022-09-02 15:26 UTC, arun3528 commented
Closing this PR , Please change the commit message and re open it

2022-09-02 15:26 UTC, closed without merging