feat(meeting-containers): decrypt function
webex/webex-js-sdk pull request #2318
Opened 2022-04-05 15:46 UTC by yjlo

# COMPLETES #< INSERT LINK TO ISSUE >
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-315399
## This pull request addresses
Being able to decrypt meeting containers
< DESCRIBE THE CONTEXT OF THE ISSUE >

## by making the following changes
Adding a new function to decrypt transforms
< DESCRIBE YOUR CHANGES >

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [x] I discussed changes with code owners prior to submitting this pull request

- [x] I have not skipped any automated checks
- [x] All existing and new tests passed
- [x] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2022-04-06 14:41 UTC, chburket requested changes
At the very least, need tests in the test function. Check the other comments, too.

2022-04-06 14:41 UTC, chburket commented on packages/node_modules/@webex/internal-plugin-conversation/src/decryption-transforms.js
> +
nit: remove extra empty lines

2022-04-07 21:12 UTC, yjlo commented on packages/node_modules/@webex/internal-plugin-conversation/src/decryption-transforms.js
> +  decryptMeetingcontainer(ctx, key, meetingContainerActivity) {
My bad spelling and typo is at fault

2022-04-07 21:12 UTC, yjlo commented on packages/node_modules/@webex/internal-plugin-conversation/src/decryption-transforms.js
> +      promises.push(ctx.transform('decryptPropDisplayName', key, meetingContainerActivity));
I agree making that change now

2022-04-07 21:29 UTC, closed without merging