feat(decrypt): meeting container activity
webex/webex-js-sdk pull request #2319
Opened 2022-04-07 21:28 UTC by yjlo

# COMPLETES
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-313496

## This pull request addresses
Decrypt meeting container activity

## by making the following changes
Add function to decrypt meeting container activity

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

1) Decrypt only displayName
2) Decrypt displayName and Topic

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [x] I discussed changes with code owners prior to submitting this pull request
- [x] I have not skipped any automated checks
- [x] All existing and new tests passed
- [x] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2022-04-08 15:26 UTC, chburket approved these changes
Looks good!

2022-04-22 21:34 UTC, robstax requested changes

2022-04-22 21:34 UTC, robstax commented on packages/node_modules/@webex/internal-plugin-conversation/src/decryption-transforms.js
> +  decryptMeetingContainer(ctx, key, meetingContainerActivity) {
this has a typo. should be `decryptMeetingcontainer` i believe

2022-04-26 21:11 UTC, robstax approved these changes

2022-05-03 16:31 UTC, robstax commented
@arun3528 this PR is blocked by failing tests unrelated to code changes. what can we do to unblock this?

2022-05-05 02:31 UTC, arun3528 commented
Can we squash the commits to one , We need it so that we can have a proper change logs

2022-05-09 11:16 UTC, closed without merging