Imc chat events
webex/webex-js-sdk pull request #2363
Opened 2022-06-08 06:46 UTC by robstax

WIP

2022-06-23 10:02 UTC, Coread requested changes
Would be great to have some tests for these

2022-06-28 23:40 UTC, robstax commented
> Would be great to have some tests for these

agreed... unfortunately the test coverage for these files and functions is already *really* bad. as far as i can tell the existing `processActivity` (which `processInmeetingchatEvent copies) is essentially untested.
`encryptActivity` is also currently untested.
all that being said, i'll work on adding tests for the cases i've implemented.

2022-07-06 17:05 UTC, InteractiveTimmy approved these changes
LGTM!

2022-07-07 15:52 UTC, Coread approved these changes

2022-07-07 16:43 UTC, merged