Swapped descriptions for auth methods
webex/webex-js-sdk pull request #2371
Opened 2022-07-05 23:56 UTC by tstatler

2022-07-05 23:58 UTC, tstatler reviewed
This PR swaps the descriptions of the implicit and auth code grant flows, which were backwards.

2024-06-19 05:33 UTC, sreenara approved these changes

2024-06-19 05:34 UTC, sreenara requested changes
@tstatler please update to the latest `next` branch and resolve the conflicts mentioned. Then we'll be good to merge this.
Thanks for taking the time to improve our repo!

2025-01-02 17:09 UTC, closed without merging

2025-01-02 17:09 UTC, sreenara commented
Closing this inactive PR