BNR - Enable BNR on device change
webex/webex-js-sdk pull request #2396
Opened 2022-07-29 04:47 UTC by mkesavan13

# COMPLETES [SPARK-346779](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-346779)

## This pull request addresses

The BNR is not enabled when a device changes. This pull request addresses that.

## by making the following changes

- Enabling BNR on updateAudio by introducing various BNR states. 
- Correcting tests appropriately

### Change Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [x] I discussed changes with code owners prior to submitting this pull request

- [x] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2022-08-02 01:18 UTC, arun3528 reviewed
Business logic looks ok

2022-08-05 08:04 UTC, meta-dipanshu-sharma requested changes

2022-08-05 08:04 UTC, meta-dipanshu-sharma commented on packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
>     * @returns {Promise<Boolean>}
I guess we're returning a Boolean value `isSuccess` not a Promise<Boolean>. Correct me if I'm missing something.

2022-08-10 11:57 UTC, mkesavan13 commented on packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
>        LoggerProxy.logger.info('Meeting:index#enableBNR. BNR enabled track obtained from WebRTC & sent to updateAudio');
Sorry missed this one out. Updated this.

2022-08-10 11:58 UTC, mkesavan13 commented on packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
>        LoggerProxy.logger.info('Meeting:index#enableBNR. BNR enabled track obtained from WebRTC & sent to updateAudio');
Thanks for pointing out @meta-dipanshu-sharma

2022-08-10 12:52 UTC, arun3528 approved these changes
Looks good to me , i thought i already review the code 

fix the package.lock file

2022-08-11 10:35 UTC, mkesavan13 commented
> Looks good to me , i thought i already review the code
> 
> fix the package.lock file

Have replaced the entire lock file. Not sure if it is the right way. Could you please check and let me know if that is okay @arun3528 ?

2022-08-12 15:05 UTC, arun3528 commented
Tested locally and samples passed , Unit tests are fixed by rajesh

2022-08-12 15:05 UTC, merged