fix: voicea bugs
webex/webex-js-sdk pull request #2458
Opened 2022-10-05 15:00 UTC by srinijay98

# COMPLETES #< INSERT LINK TO ISSUE >

## This pull request addresses

< DESCRIBE THE CONTEXT OF THE ISSUE >

## by making the following changes

< DESCRIBE YOUR CHANGES >

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2022-10-05 16:09 UTC, arun3528 submitted a review, later dismissed
We should move away from extending llm on voicia and directly using the plugin llm there similar to meetings

2022-10-06 13:39 UTC, mkesavan13 requested changes
Looks good to me. Just couple of changes,

- We need not checkin webex.min.js. Kindly remove it from the commit. 
- If all these changes relate to internal-plugin-voicea, please squash all commits and mention the plugin in the commit like `fix(interna-plugin-voicea): COMMIT_MESSAGE` as stated in the [contribution guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md) and that helps in having a cleaner history and change log

2022-10-06 13:39 UTC, mkesavan13 commented on packages/node_modules/@webex/internal-plugin-llm/src/llm.ts
> +    console.error(e);
Shouldn't we be using Logger plugin instead of `console.error` ?

2022-10-06 13:44 UTC, srinijay98 commented on packages/node_modules/@webex/internal-plugin-voicea/src/voicea.ts
> +          timestamp: millisToMinutesAndSeconds(voiceaPayload.transcript.end_millis)
my calculation was wrong
transcription starts at 10000ms and ends at 15000 -> this means the transcript timestamp is 150000
instead 15000-10000 = 5000ms = 5s was a wrong timestamp

2022-10-06 15:27 UTC, Coread approved these changes

2022-10-07 08:02 UTC, mkesavan13 approved these changes

2022-10-07 08:10 UTC, merged