fix: update WCME deps
webex/webex-js-sdk pull request #2531
Opened 2022-12-09 18:24 UTC by marcin-bazyl

This PR is for updating SDK beta to latest WCME dependencies - they are all public now.

This for now includes just the code change required to make it work with these latest dependencies (it was tested using local linking). It needs to be updated to use the right version of "@webex/internal-media-core" once that version is published.

2022-12-09 23:03 UTC, arun3528 approved these changes

2022-12-09 23:06 UTC, arun3528 requested changes
I got see the changes for version here

2022-12-12 17:56 UTC, marcin-bazyl commented
update the PR to use the latest webrtc-media lib, it's ready now

2022-12-12 18:00 UTC, arun3528 approved these changes

2022-12-12 18:15 UTC, arun3528 commented
failing flaky test

2022-12-12 18:16 UTC, merged