Feat/add update breakout
webex/webex-js-sdk pull request #2735
Opened 2023-04-13 04:53 UTC by othellashao

# COMPLETES #
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-421079

## This pull request addresses

add the missing api of updating breakout information to server

## by making the following changes

1. add update breakout api and unit test of it
2. add protection for edit lock

### Change Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [x] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2023-04-13 07:53 UTC, Coread commented on packages/@webex/plugin-meetings/src/breakouts/index.ts
> +        window.clearInterval(this.intervalID);
issue: you should add a test to make sure you clear the interval

2023-04-13 07:54 UTC, Coread commented on packages/@webex/plugin-meetings/src/breakouts/index.ts
> +    if (editlock && breakout.body?.editlock?.token) {
issue: I don't see a test checking this case

2023-04-13 07:55 UTC, Coread commented on packages/@webex/plugin-meetings/src/breakouts/index.ts
> +        boServiceErrorHandler(error, 'Breakouts#update --> Edit lock token mismatch')
issue: I can't see a test checking this reject

2023-04-13 07:56 UTC, Coread requested changes
please see comments

2023-04-13 12:39 UTC, Coread commented on packages/@webex/plugin-meetings/src/breakouts/index.ts
> +        boServiceErrorHandler(error, 'Breakouts#update --> Edit lock token mismatch')
@othellashao are you sure the message here 'Breakouts#update --> Edit lock token mismatch' is correct? Given that other errors are possible perhaps just "Breakouts#update" might be better

2023-04-14 10:38 UTC, closed without merging

2023-04-14 10:39 UTC, othellashao commented
Can't push change on it since the branch was protected. Create new PR on it