fix(webex): style test fix
webex/webex-js-sdk pull request #3145
Opened 2023-10-11 05:37 UTC by Kesari3008

# COMPLETES #< INSERT LINK TO ISSUE >

## This pull request addresses
For webex package, style test and unit tests are failing so added fix.

## by making the following changes
Added eslint in webex package.json dev dependencies

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2023-10-18 17:33 UTC, sreenara requested changes
Have a comment regarding the version. 
Also, let's check what's causing the UT to fail in the pipeline. Apart from that the changes look ok.

2023-10-24 08:32 UTC, Kesari3008 commented on packages/calling/package.json
> +    "eslint": "^8.24.0",
This is what is being used in other packages so updated it in calling also

2023-10-24 17:33 UTC, arun3528 commented on packages/webex/test/unit/spec/webex.js
> +        const servicesGetStub = sinon.stub(webex.internal.services, 'get');
sorry did not see this message , we will need to do a bug bash for this , I did a similar session with @mkesavan13 
its not easy its little hard to figure out all the test which are causing this 

better to have a meeting to go over it

2023-10-26 18:21 UTC, sreenara approved these changes

2023-10-26 18:26 UTC, merged