feat(ca): add identifiers confId, mid
webex/webex-js-sdk pull request #3226
Opened 2023-12-03 00:37 UTC by chrisadubois

# COMPLETES 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-452762
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-462077
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-473895

## This pull request addresses

Add globalMeetingId and webexConferenceIdStr from either meetingInfo when a meeting object is available, OR from options passed in by consumers

## by making the following changes
updating the client metrics plugin
adding the params directly from the meetinginfo.response
update types

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

Manual tests (guest and login) meeting joins

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [x] I discussed changes with code owners prior to submitting this pull request

- [x] I have not skipped any automated checks
- [x] All existing and new tests passed
- [x] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2023-12-06 10:48 UTC, torgeadelin commented on packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
> +describe.only('internal-plugin-metrics', () => {
remove .only

2023-12-06 10:53 UTC, torgeadelin commented on packages/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.ts
> +                webexConferenceIdStr: response?.body?.confID,
use options instead of payload

2023-12-06 10:53 UTC, torgeadelin requested changes
few blocking comments, but looking good

2023-12-06 16:15 UTC, chrisadubois commented on packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
> +describe.only('internal-plugin-metrics', () => {
nice catch ty

2023-12-06 16:35 UTC, chrisadubois commented on packages/@webex/plugin-meetings/src/meeting-info/index.ts
> +                webexConferenceIdStr: info?.body?.confID,
done

2023-12-06 16:35 UTC, chrisadubois commented
all requested changes complete

2023-12-07 10:32 UTC, torgeadelin approved these changes

2023-12-07 10:40 UTC, robstax approved these changes
small typo in test description, but non-blocking

2023-12-07 10:41 UTC, merged