fix(callforwarding): changes to implement callforwarding for UCM users
webex/webex-js-sdk pull request #3367
Opened 2024-02-08 08:42 UTC by sokn-sys

# COMPLETES #< INSERT LINK TO ISSUE >

## This pull request addresses

< DESCRIBE THE CONTEXT OF THE ISSUE >

## by making the following changes

< DESCRIBE YOUR CHANGES >

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2024-02-09 10:28 UTC, Shreyas281299 requested changes
The changes look good. Please add a test where cfa is assigned as the e164Number when dn is not present.

2024-02-09 11:42 UTC, karthikraji2020 requested changes
@sokn-sys could you please provide more context to this PR?

2024-02-12 05:13 UTC, sokn-sys commented
> The changes look good. Please add a test where cfa is assigned as the e164Number when dn is not present.

Addressed the review comments

2024-02-12 05:15 UTC, sokn-sys commented
> @sokn-sys could you please provide more context to this PR?

Updated the context and added one more Jira for reference.

2024-02-12 08:33 UTC, sreenara approved these changes
Small comment

2024-02-12 08:33 UTC, sreenara commented on packages/calling/src/CallSettings/UcmBackendConnector.test.ts
> +    it('Success: Get Call Forward Always setting when directory num matchcing with e16number and set to destination', async () => {
Can we fix the typo in the word matching?

2024-02-12 08:41 UTC, Shreyas281299 approved these changes
LGTM

2024-02-12 10:15 UTC, karthikraji2020 approved these changes
changes LGTM

2024-02-12 12:49 UTC, merged