fix: latest commits from beta
webex/webex-js-sdk pull request #3435
Opened 2024-03-11 06:51 UTC by Parimala032

# COMPLETES #< INSERT LINK TO ISSUE >

## This pull request addresses

< DESCRIBE THE CONTEXT OF THE ISSUE >

## by making the following changes

< DESCRIBE YOUR CHANGES >

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2024-03-15 07:09 UTC, Shreyas281299 approved these changes
LGTM

2024-03-18 09:36 UTC, Shreyas281299 requested changes
Reverting approval, lets add the latest commits from beta as well.

2024-03-19 13:10 UTC, Shreyas281299 approved these changes
LGTM

2024-03-20 06:25 UTC, sreenara commented on packages/@webex/internal-plugin-metrics/package.json
> -    "test:browser": "webex-legacy-tools test --integration --unit --runner karma",
This is removed because there are no browser tests for the metrics plugin.

2024-03-20 08:22 UTC, sreenara approved these changes

2024-03-20 08:22 UTC, merged