Update CONTRIBUTING.md
webex/webex-js-sdk pull request #3680
Opened 2024-07-02 11:41 UTC by Kesari3008

# COMPLETES #Ad-Hoc

## This pull request addresses
Updating the build command in the contributing.md file as per new tooling

## by making the following changes
Updating the build command in the contributing.md file as per new tooling

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2024-07-02 12:39 UTC, mkesavan13 approved these changes
Looks good to me

2024-07-02 12:41 UTC, mkesavan13 requested changes
The PR is raised against master branch.

Kindly check and raise against the next branch.

2024-10-22 07:40 UTC, sreenara commented
@Kesari3008 do we need this PR open?

2025-01-02 16:58 UTC, sreenara commented
Closing this inactive PR

2025-01-02 16:58 UTC, closed without merging