feat(calling): add rtcstat functionality to calling
webex/webex-js-sdk pull request #3835
Opened 2024-09-16 07:23 UTC by rarajes2

# COMPLETES #< [SPARK-529191](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-529191) >

## This pull request addresses

Adds the rtcstats to the calling SDK

## by making the following changes

Able to send the rtcstats with the calling SDK APIs.

<img width="1326" alt="Screenshot 2024-09-13 at 7 08 17 PM" src="https://github.com/user-attachments/assets/b36ff366-0e94-4827-9805-2b030284ce55">

**Note**: For HAR file, please check the JIRA ticket.

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2024-09-17 14:13 UTC, mkesavan13 requested changes

2024-09-17 14:13 UTC, mkesavan13 commented on packages/@webex/internal-plugin-metrics/src/rtcMetrics/index.ts
> +  constructor(webex, correlationId, meetingId, callId) {
Why are we rearranging the params here?

2024-09-17 14:13 UTC, mkesavan13 commented on packages/@webex/plugin-meetings/src/meeting/index.ts
> +  RtcMetrics,
The param change [here](https://github.com/webex/webex-js-sdk/blob/b6fd626956725c6047eeca9827724eb847cdc911/packages/%40webex/internal-plugin-metrics/src/rtcMetrics/index.ts#L50) is not handled in this file [here](https://github.com/webex/webex-js-sdk/blob/b6fd626956725c6047eeca9827724eb847cdc911/packages/%40webex/plugin-meetings/src/meeting/index.ts#L6315)

2024-09-17 14:13 UTC, mkesavan13 commented on packages/calling/src/CallingClient/calling/call.test.ts
>      );
What are these 3 functions? Where does it come from?

2024-09-17 14:13 UTC, mkesavan13 commented on packages/calling/src/CallingClient/calling/call.ts
> +    this.mediaConnection?.on(
Why do we need these operators here? Is there a scenario where the `mediaConnection` would not exist now?

2024-09-28 05:58 UTC, rarajes2 commented
Closing this PR. Will raise 2 PRs for this
1. Moving the RtcMetrics to internal-plugin-metrics
2. Introducing RtcStats in the Calling

2024-09-28 05:58 UTC, closed without merging