fix(byods-docs): added readme file
webex/webex-js-sdk pull request #3901
Opened 2024-10-10 03:51 UTC by Parimala032

# COMPLETES #< INSERT LINK TO ISSUE >

## This pull request addresses

< DESCRIBE THE CONTEXT OF THE ISSUE >

## by making the following changes

< DESCRIBE YOUR CHANGES >

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios were tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2024-10-14 11:13 UTC, adhmenon commented on packages/byods/README.md
> +  yarn run samples:serve
```suggestion
  yarn workspace @webex/byods-demo-server dev:hot
```
Will need to get the demo server changes in order for this to work though.

2024-10-16 09:15 UTC, adhmenon commented on packages/byods/README.md
> +yarn workspaces foreach --parallel --verbose run build:src
We can remove this.. no need to run for each package.

2024-10-16 09:55 UTC, adhmenon commented on packages/byods/README.md
> +yarn build:src
```suggestion
yarn workspace @webex/byods run build:src
```

2024-10-16 09:55 UTC, adhmenon commented on packages/byods/README.md
> +yarn workspaces foreach --parallel --verbose run build:src
We can remove this.... no need to run all.

2024-10-16 10:15 UTC, adhmenon approved these changes
LGTM.

2024-10-17 04:15 UTC, bhabalan requested changes

2024-10-17 04:15 UTC, bhabalan commented on packages/byods/README.md
> +With the BYoDS SDK, you can easily integrate device management capabilities into your Webex applications, allowing users to bring their own devices seamlessly into the Webex ecosystem.
Can you please check this description? This is not aligned with what the BYoDS SDK does.

2024-10-17 04:15 UTC, bhabalan commented on packages/byods/README.md
> +# CDN
We won't be doing CDN deployment as it's a server side SDK

2024-10-17 12:42 UTC, bhabalan approved these changes

2024-10-17 12:42 UTC, merged