Feat/practice session - start/stop control API and displayhint
webex/webex-js-sdk pull request #4008
Opened 2024-11-27 02:43 UTC by mickelr

# COMPLETES #< INSERT LINK TO ISSUE >

## This pull request addresses

< DESCRIBE THE CONTEXT OF THE ISSUE >

## by making the following changes

< DESCRIBE YOUR CHANGES >

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios were tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

2024-12-06 09:29 UTC, Shreyas281299 commented
@coderabbit review

2024-12-06 09:30 UTC, Shreyas281299 requested changes
Please add the manual tests performed in the test description.

2024-12-09 01:06 UTC, mickelr commented
> Please add the manual tests performed in the PR description.

Done

2024-12-16 06:38 UTC, Shreyas281299 approved these changes
Looks good to me, please see a query that I had.

2024-12-16 06:38 UTC, Shreyas281299 commented on packages/@webex/plugin-meetings/src/webinar/index.ts
> +  setPracticeSessionState(enabled) {
Question: can you point me to where we are using this method, I was unable to find it

2024-12-16 06:44 UTC, JudyZhuHz approved these changes
LGTM

2024-12-16 06:44 UTC, merged